#pragma once

#ifdef LOCAL_RU
#define str_output_settings "Выходные настройки"
#define str_info_page_decsr "Этот помощник сгенерирует настройки алгоритма расчета сдвигового спутникового ветра и применит его для последовательности спутниковых снимков"
#define str_select "Выбрать"
#define str_input_files_msg_path "Путь к входных файлам(MSG)"
#define str_output_files_jpg_path "Путь к выходных файлам(JPG)"
#define str_input_files_shp_path "Путь к векторным файлам(SHP)"
#define str_output_file_name_prefix "Префикс имени выходных файлов"
#define str_satellite_type "Тип спутника MSG 4/3"
#define str_channel "Канал"
#define str_hours_sc_min "Часы::Минуты"
#define str_datetime_page_title "Задание временного слота"
#define str_date_from "Дата от"
#define str_date_to "Дата до"
#define str_visual_style "Стиль отрисовки"
#define str_vector_layers "Векторные слои"
#define str_file_name "Имя файла"
#define str_dbf_params "DBF параметры"
#define str_text_color "Цвет текста"
#define str_line_color "Цвет линий"
#define str_line_width "Толщина линий"
#define str_line_style "Стиль линий"
#define str_font_name "Имя фонта"
#define str_size "Размер"
#define str_add_layer "Добавить слой"
#define str_load "Загрузить"
#define str_remove_layer "Удалить слой"
#define str_wind_arrows "Cтрелки ветра"
#define str_color "Цвет"
#define str_width_depth "Толщина"
#define str_region_page_title "Определение географического региона расчета"
#define str_grid_step "Шаг сетки"
#define str_time_slot_undermine_message "Выберите больше временных слотов, чтобы построить поле ветра!"
#define str_error_blank "Ошибка  "
#define str_generation_succeeded "Геренация прошла успешно!"
#define str_saving_nocap "сохранение"
#define str_data_processing_wizard "Мастер настройки обработки"

#else
#define str_output_settings "Output Settings"
#define str_info_page_decsr "This wizard generates the athmosphere displacement wind fields settings and apply them to the sequince of satellite images"
#define str_select "Select"
#define str_input_files_msg_path "Input Files(MSG) Path"
#define str_output_files_jpg_path "Output Files(JPG) Path"
#define str_input_files_shp_path "Vector Files(SHP) Path"
#define str_output_file_name_prefix "Output File Name Prefix"
#define str_satellite_type "Satellite Type MSG 4/3"
#define str_channel "Channel"
#define str_hours_sc_min "Hours::Minutes"
#define str_datetime_page_title "DateTime Slots Selection"
#define str_date_from "Date From"
#define str_date_to "Date To"
#define str_visual_style "Visual Style"
#define str_vector_layers "Vector Layers"
#define str_file_name "File Name"
#define str_dbf_params "DBF Params"
#define str_text_color "Text Color"
#define str_line_color "Line Color"
#define str_line_width "Line Width"
#define str_line_style "Line Style"
#define str_font_name "Font Name"
#define str_size "Size"
#define str_add_layer "Add Layer"
#define str_load "Load"
#define str_remove_layer "Remove Layer"
#define str_wind_arrows "Wind Arrows"
#define str_color "Color"
#define str_width_depth "Width"
#define str_region_page_title "Geographical Region Selection"
#define str_grid_step "Grid Step"
#define str_time_slot_undermine_message "Select more timeslots to make wind field, please!"
#define str_error_blank "Error  "
#define str_generation_succeeded "Generation Succeeded!"
#define str_data_processing_wizard "Data Processing Wizard"

#endif
